from datetime import datetime
from src.risk_scoring import RISK_EMOJI, RISK_COLOR

# fpdf2 is a pure-Python, MIT/LGPL-licensed PDF library (no system binaries,
# no paid tier — free as in both "no cost" and "open source"). It's the
# lightest-weight way to add a "download as PDF" option per the project's
# business plan, without pulling in a heavyweight HTML→PDF toolchain
# (e.g. WeasyPrint, which needs system-level Cairo/Pango libraries).
from fpdf import FPDF

_BREAKDOWN_LABELS = (
    ("explanation", "Plain-language explanation"),
    ("why_it_matters", "Why it matters"),
    ("financial_impact", "Potential financial impact"),
    ("suggested_action", "Suggested action before signing"),
)


def generate_report(results: list[dict], source_name: str = "contract", exposure_items: list[dict] | None = None) -> str:
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M")

    by_level: dict[str, list[dict]] = {
        "High": [], "Medium": [], "Low": [], "Informational": []
    }
    for r in results:
        by_level[r["risk"]].append(r)

    lines = [
        "# FinClariX Contract Analysis Report",
        "",
        f"**Generated:** {timestamp}",
        f"**Source:** {source_name}",
        "",
        "---",
        "",
        "## Summary",
        "",
        "| Risk Level | Clauses |",
        "|---|:---:|",
    ]
    for level in ("High", "Medium", "Low", "Informational"):
        emoji = RISK_EMOJI[level]
        lines.append(f"| {emoji} {level} | {len(by_level[level])} |")

    lines += ["", "---", ""]

    if exposure_items:
        lines += [
            "## 💰 Financial Exposure Summary",
            "",
            "_Figures below are computed deterministically from amounts and time "
            "periods stated directly in the contract — not estimated by AI._",
            "",
        ]
        for item in exposure_items:
            lines.append(f"- {item['text']}")
        lines += ["", "---", ""]

    for level in ("High", "Medium", "Low", "Informational"):
        group = by_level[level]
        if not group:
            continue
        emoji = RISK_EMOJI[level]
        lines.append(f"## {emoji} {level} Risk Clauses")
        lines.append("")
        for i, clause in enumerate(group, 1):
            preview = clause["text"][:300] + ("…" if len(clause["text"]) > 300 else "")
            lines += [
                f"### Clause {i}",
                "",
                f"> {preview}",
                "",
            ]
            if clause.get("keywords"):
                kw_list = "`, `".join(clause["keywords"])
                lines.append(f"**Flagged terms:** `{kw_list}`")
                lines.append("")
            breakdown = clause.get("breakdown")
            if breakdown:
                for key, label in _BREAKDOWN_LABELS:
                    value = breakdown.get(key)
                    if value:
                        lines.append(f"**{label}:** {value}")
                        lines.append("")
        lines += ["---", ""]

    lines += [
        "_Report generated by [FinClariX](https://github.com/myriiiaamm/finclarix) — "
        "Finance that sticks, minus the tricks._",
    ]
    return "\n".join(lines)


# ── PDF export ────────────────────────────────────────────────────────────────
# The downloadable report stays in English (see the call site in app.py for
# why), which means it's always safe to render with fpdf2's built-in core
# fonts (Helvetica). Those core fonts only cover the Latin-1 character set —
# no embedded TTF needed, no extra files to ship — so `_pdf_safe()` below
# simply replaces any stray non-Latin-1 character (e.g. if an AI-localised
# overlay slipped in some non-English wording) with "?" rather than crashing.
# Anyone who needs full Unicode fidelity can still use the Markdown download.

_RISK_LABEL = {
    "High": "[ HIGH RISK ]",
    "Medium": "[ MEDIUM RISK ]",
    "Low": "[ LOW RISK ]",
    "Informational": "[ INFORMATIONAL ]",
}


def _hex_to_rgb(hex_color: str) -> tuple[int, int, int]:
    hex_color = hex_color.lstrip("#")
    return tuple(int(hex_color[i:i + 2], 16) for i in (0, 2, 4))  # type: ignore[return-value]


def _pdf_safe(text: str) -> str:
    """Make `text` safe for fpdf2's Latin-1-only core fonts (see module note
    above). Degrades gracefully instead of raising `FPDFUnicodeEncodingException`."""
    return text.encode("latin-1", "replace").decode("latin-1")


def generate_report_pdf(
    results: list[dict],
    source_name: str = "contract",
    exposure_items: list[dict] | None = None,
) -> bytes:
    """Build a polished PDF version of the same report `generate_report()`
    produces as Markdown — summary table, financial exposure summary, then
    each clause grouped by risk level with its plain-language breakdown.

    Returns raw PDF bytes, ready to hand straight to `st.download_button`."""
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M")

    by_level: dict[str, list[dict]] = {
        "High": [], "Medium": [], "Low": [], "Informational": []
    }
    for r in results:
        by_level[r["risk"]].append(r)

    pdf = FPDF(format="A4")
    pdf.set_auto_page_break(auto=True, margin=18)
    pdf.set_margins(18, 16, 18)
    pdf.add_page()

    # ── Header ───────────────────────────────────────────────────────────────
    pdf.set_font("Helvetica", "B", 18)
    pdf.cell(0, 10, _pdf_safe("FinClariX Contract Analysis Report"), new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(110, 110, 110)
    pdf.cell(0, 6, _pdf_safe(f"Generated: {timestamp}    |    Source: {source_name}"),
             new_x="LMARGIN", new_y="NEXT")
    pdf.set_text_color(0, 0, 0)
    pdf.ln(4)

    # ── Summary ──────────────────────────────────────────────────────────────
    pdf.set_font("Helvetica", "B", 13)
    pdf.cell(0, 8, "Summary", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "", 11)
    for level in ("High", "Medium", "Low", "Informational"):
        r, g, b = _hex_to_rgb(RISK_COLOR[level])
        pdf.set_text_color(r, g, b)
        pdf.set_font("Helvetica", "B", 10)
        pdf.cell(38, 7, _pdf_safe(_RISK_LABEL[level]))
        pdf.set_text_color(0, 0, 0)
        pdf.set_font("Helvetica", "", 11)
        pdf.cell(0, 7, f"{len(by_level[level])} clause(s)", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(3)

    # ── Financial exposure summary ───────────────────────────────────────────
    if exposure_items:
        pdf.set_font("Helvetica", "B", 13)
        pdf.cell(0, 8, "Financial Exposure Summary", new_x="LMARGIN", new_y="NEXT")
        pdf.set_font("Helvetica", "I", 9)
        pdf.set_text_color(110, 110, 110)
        pdf.multi_cell(0, 5, _pdf_safe(
            "Figures below are computed deterministically from amounts and "
            "time periods stated directly in the contract — not estimated by AI."
        ))
        pdf.set_text_color(0, 0, 0)
        pdf.set_font("Helvetica", "", 11)
        for item in exposure_items:
            pdf.multi_cell(190, 6, _pdf_safe(f"-  {item['text']}"))
        pdf.ln(3)

    # ── Clauses, grouped by risk level ───────────────────────────────────────
    for level in ("High", "Medium", "Low", "Informational"):
        group = by_level[level]
        if not group:
            continue

        r, g, b = _hex_to_rgb(RISK_COLOR[level])
        pdf.set_font("Helvetica", "B", 13)
        pdf.set_text_color(r, g, b)
        pdf.cell(0, 9, _pdf_safe(f"{_RISK_LABEL[level]}  {level} Risk Clauses"),
                 new_x="LMARGIN", new_y="NEXT")
        pdf.set_text_color(0, 0, 0)
        pdf.ln(1)

        for i, clause in enumerate(group, 1):
            preview = clause["text"][:300] + ("…" if len(clause["text"]) > 300 else "")

            pdf.set_font("Helvetica", "B", 11)
            pdf.cell(0, 7, _pdf_safe(f"Clause {i}"), new_x="LMARGIN", new_y="NEXT")

            pdf.set_font("Helvetica", "I", 9)
            pdf.set_text_color(90, 90, 90)
            pdf.multi_cell(0, 5, _pdf_safe(f"“{preview}”"))
            pdf.set_text_color(0, 0, 0)

            if clause.get("keywords"):
                pdf.set_font("Helvetica", "B", 9)
                pdf.write(5, _pdf_safe("Flagged terms: "))
                pdf.set_font("Helvetica", "", 9)
                pdf.multi_cell(0, 5, _pdf_safe(", ".join(clause["keywords"])))

            breakdown = clause.get("breakdown")
            if breakdown:
                pdf.ln(1)
                for key, label in _BREAKDOWN_LABELS:
                    value = breakdown.get(key)
                    if not value:
                        continue
                    pdf.set_font("Helvetica", "B", 10)
                    pdf.multi_cell(190, 5.5, _pdf_safe(f"{label}:"))
                    pdf.set_font("Helvetica", "", 10)
                    pdf.multi_cell(190, 5.5, _pdf_safe(value))
                    pdf.ln(1)

            pdf.ln(4)

    # ── Footer note ──────────────────────────────────────────────────────────
    pdf.set_font("Helvetica", "I", 8)
    pdf.set_text_color(130, 130, 130)
    pdf.multi_cell(0, 5, _pdf_safe(
        "Report generated by FinClariX (github.com/myriiiaamm/finclarix) — "
        "Finance that sticks, minus the tricks."
    ))

    # `pdf.output()` returns a `bytearray` in fpdf2 ≥ 2.5 — `bytes()` makes it
    # directly compatible with `st.download_button(data=...)`.
    return bytes(pdf.output())
