from datetime import datetime
from src.risk_scoring import RISK_EMOJI, RISK_COLOR
from src.i18n import t

# fpdf2 is a pure-Python, MIT/LGPL-licensed PDF library (no system binaries,
# no paid tier — free as in both "no cost" and "open source"). It's the
# lightest-weight way to add a "download as PDF" option per the project's
# business plan, without pulling in a heavyweight HTML→PDF toolchain
# (e.g. WeasyPrint, which needs system-level Cairo/Pango libraries).
from fpdf import FPDF

# Maps clause breakdown dict keys → i18n label keys (same as app.py)
_BREAKDOWN_LABEL_KEYS = (
    ("explanation", "label_explanation"),
    ("why_it_matters", "label_why"),
    ("financial_impact", "label_financial_impact"),
    ("suggested_action", "label_suggested_action"),
)

_LEVEL_METRIC_KEY = {
    "High": "metric_high",
    "Medium": "metric_medium",
    "Low": "metric_low",
    "Informational": "metric_informational",
}


def generate_report(results: list[dict], source_name: str = "contract", exposure_items: list[dict] | None = None) -> str:
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M")

    by_level: dict[str, list[dict]] = {
        "High": [], "Medium": [], "Low": [], "Informational": []
    }
    for r in results:
        by_level[r["risk"]].append(r)

    lines = [
        "# FinClariX Contract Analysis Report",
        "",
        f"**Generated:** {timestamp}",
        f"**Source:** {source_name}",
        "",
        "---",
        "",
        "## Summary",
        "",
        "| Risk Level | Clauses |",
        "|---|:---:|",
    ]
    for level in ("High", "Medium", "Low", "Informational"):
        emoji = RISK_EMOJI[level]
        lines.append(f"| {emoji} {level} | {len(by_level[level])} |")

    lines += ["", "---", ""]

    if exposure_items:
        lines += [
            "## Financial Exposure Summary",
            "",
            "_Figures below are computed deterministically from amounts and time "
            "periods stated directly in the contract — not estimated by AI._",
            "",
        ]
        for item in exposure_items:
            lines.append(f"- {item['text']}")
        lines += ["", "---", ""]

    for level in ("High", "Medium", "Low", "Informational"):
        group = by_level[level]
        if not group:
            continue
        emoji = RISK_EMOJI[level]
        lines.append(f"## {emoji} {level} Risk Clauses")
        lines.append("")
        for i, clause in enumerate(group, 1):
            preview = clause["text"][:300] + ("..." if len(clause["text"]) > 300 else "")
            lines += [
                f"### Clause {i}",
                "",
                f"> {preview}",
                "",
            ]
            if clause.get("keywords"):
                kw_list = "`, `".join(clause["keywords"])
                lines.append(f"**Flagged terms:** `{kw_list}`")
                lines.append("")
            breakdown = clause.get("breakdown")
            if breakdown:
                for key, label_key in _BREAKDOWN_LABEL_KEYS:
                    value = breakdown.get(key)
                    if value:
                        label = t(label_key, "English")
                        lines.append(f"**{label}:** {value}")
                        lines.append("")
        lines += ["---", ""]

    lines += [
        "_Report generated by [FinClariX](https://github.com/myriiiaamm/finclarix) -- "
        "Finance that sticks, minus the tricks._",
    ]
    return "\n".join(lines)


# ── PDF export ────────────────────────────────────────────────────────────────

def _hex_to_rgb(hex_color: str) -> tuple[int, int, int]:
    hex_color = hex_color.lstrip("#")
    return tuple(int(hex_color[i:i + 2], 16) for i in (0, 2, 4))  # type: ignore[return-value]


_UNICODE_TO_LATIN1 = str.maketrans({
    "…": "...",   # … ellipsis
    "—": "--",    # — em dash
    "–": "-",     # – en dash
    "“": '"',     # " left double quotation mark
    "”": '"',     # " right double quotation mark
    "‘": "'",     # ' left single quotation mark
    "’": "'",     # ' right single quotation mark
    "€": "EUR",   # € euro sign (outside Latin-1 range)
    " ": " ",     # non-breaking space
    "•": "-",     # • bullet
    "−": "-",     # − minus sign
})


def _pdf_safe(text: str) -> str:
    """Substitute common out-of-range Unicode chars, then encode to Latin-1."""
    return text.translate(_UNICODE_TO_LATIN1).encode("latin-1", "replace").decode("latin-1")


def generate_report_pdf(
    results: list[dict],
    source_name: str = "contract",
    exposure_items: list[dict] | None = None,
    lang: str = "English",
) -> bytes:
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M")

    by_level: dict[str, list[dict]] = {
        "High": [], "Medium": [], "Low": [], "Informational": []
    }
    for r in results:
        by_level[r["risk"]].append(r)

    pdf = FPDF(format="A4")
    pdf.set_auto_page_break(auto=True, margin=18)
    pdf.set_margins(18, 16, 18)
    pdf.add_page()

    # ── Header ───────────────────────────────────────────────────────────────
    pdf.set_font("Helvetica", "B", 18)
    pdf.cell(0, 10, _pdf_safe("FinClariX Contract Analysis Report"), new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(110, 110, 110)
    pdf.cell(0, 6, _pdf_safe(f"Generated: {timestamp}    |    Source: {source_name}"),
             new_x="LMARGIN", new_y="NEXT")
    pdf.set_text_color(0, 0, 0)
    pdf.ln(4)

    # ── Summary ──────────────────────────────────────────────────────────────
    pdf.set_font("Helvetica", "B", 13)
    pdf.cell(0, 8, "Summary", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "", 11)
    for level in ("High", "Medium", "Low", "Informational"):
        ri, g, b = _hex_to_rgb(RISK_COLOR[level])
        pdf.set_text_color(ri, g, b)
        pdf.set_font("Helvetica", "B", 10)
        pdf.cell(42, 7, _pdf_safe(t(_LEVEL_METRIC_KEY[level], lang)))
        pdf.set_text_color(0, 0, 0)
        pdf.set_font("Helvetica", "", 11)
        pdf.cell(0, 7, str(len(by_level[level])), new_x="LMARGIN", new_y="NEXT")
    pdf.ln(3)

    # ── Financial exposure summary ───────────────────────────────────────────
    if exposure_items:
        pdf.set_font("Helvetica", "B", 13)
        pdf.cell(0, 8, _pdf_safe(t("exposure_title", lang)), new_x="LMARGIN", new_y="NEXT")
        pdf.set_font("Helvetica", "", 11)
        for item in exposure_items:
            pdf.multi_cell(190, 6, _pdf_safe(f"-  {item['text']}"), new_x="LMARGIN", new_y="NEXT")
        pdf.ln(3)

    # ── Clauses, grouped by risk level ───────────────────────────────────────
    for level in ("High", "Medium", "Low", "Informational"):
        group = by_level[level]
        if not group:
            continue

        ri, g, b = _hex_to_rgb(RISK_COLOR[level])
        pdf.set_font("Helvetica", "B", 13)
        pdf.set_text_color(ri, g, b)
        pdf.cell(0, 9, _pdf_safe(t(_LEVEL_METRIC_KEY[level], lang)),
                 new_x="LMARGIN", new_y="NEXT")
        pdf.set_text_color(0, 0, 0)
        pdf.ln(1)

        for i, clause in enumerate(group, 1):
            preview = clause["text"][:300] + ("..." if len(clause["text"]) > 300 else "")

            pdf.set_font("Helvetica", "B", 11)
            pdf.cell(0, 7, _pdf_safe(f"Clause {i}"), new_x="LMARGIN", new_y="NEXT")

            pdf.set_font("Helvetica", "I", 9)
            pdf.set_text_color(90, 90, 90)
            pdf.multi_cell(190, 5, _pdf_safe(f'"{preview}"'), new_x="LMARGIN", new_y="NEXT")
            pdf.set_text_color(0, 0, 0)

            if clause.get("keywords"):
                pdf.set_font("Helvetica", "B", 9)
                pdf.write(5, _pdf_safe(t("flagged_terms", lang) + ": "))
                pdf.set_font("Helvetica", "", 9)
                pdf.multi_cell(0, 5, _pdf_safe(", ".join(clause["keywords"])), new_x="LMARGIN", new_y="NEXT")

            breakdown = clause.get("breakdown")
            if breakdown:
                pdf.ln(1)
                for key, label_key in _BREAKDOWN_LABEL_KEYS:
                    value = breakdown.get(key)
                    if not value:
                        continue
                    pdf.set_font("Helvetica", "B", 10)
                    pdf.multi_cell(190, 5.5, _pdf_safe(f"{t(label_key, lang)}:"), new_x="LMARGIN", new_y="NEXT")
                    pdf.set_font("Helvetica", "", 10)
                    pdf.multi_cell(190, 5.5, _pdf_safe(value), new_x="LMARGIN", new_y="NEXT")
                    pdf.ln(1)

            pdf.ln(4)

    # ── Footer note ──────────────────────────────────────────────────────────
    pdf.set_font("Helvetica", "I", 8)
    pdf.set_text_color(130, 130, 130)
    pdf.multi_cell(190, 5, _pdf_safe(
        "Report generated by FinClariX (github.com/myriiiaamm/finclarix) -- "
        "Finance that sticks, minus the tricks."
    ), new_x="LMARGIN", new_y="NEXT")

    return bytes(pdf.output())
