from datetime import datetime
from src.risk_scoring import RISK_EMOJI


def generate_report(results: list[dict], source_name: str = "contract") -> str:
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M")

    by_level: dict[str, list[dict]] = {
        "High": [], "Medium": [], "Low": [], "Informational": []
    }
    for r in results:
        by_level[r["risk"]].append(r)

    lines = [
        "# FinClariX Contract Analysis Report",
        "",
        f"**Generated:** {timestamp}",
        f"**Source:** {source_name}",
        "",
        "---",
        "",
        "## Summary",
        "",
        "| Risk Level | Clauses |",
        "|---|:---:|",
    ]
    for level in ("High", "Medium", "Low", "Informational"):
        emoji = RISK_EMOJI[level]
        lines.append(f"| {emoji} {level} | {len(by_level[level])} |")

    lines += ["", "---", ""]

    for level in ("High", "Medium", "Low", "Informational"):
        group = by_level[level]
        if not group:
            continue
        emoji = RISK_EMOJI[level]
        lines.append(f"## {emoji} {level} Risk Clauses")
        lines.append("")
        for i, clause in enumerate(group, 1):
            preview = clause["text"][:300] + ("…" if len(clause["text"]) > 300 else "")
            lines += [
                f"### Clause {i}",
                "",
                f"> {preview}",
                "",
            ]
            if clause.get("keywords"):
                kw_list = "`, `".join(clause["keywords"])
                lines.append(f"**Flagged terms:** `{kw_list}`")
                lines.append("")
            if clause.get("explanation"):
                lines.append(f"**Plain-language explanation:** {clause['explanation']}")
                lines.append("")
        lines += ["---", ""]

    lines += [
        "_Report generated by [FinClariX](https://github.com/myriiiaamm/finclarix) — "
        "Finance that sticks, minus the tricks._",
    ]
    return "\n".join(lines)
